# Prompt Preview

Ce notebook lit `data/raw/swissdox_input.parquet`, formate chaque article dans le template de prompt défini dans `src/prompts.py`, et produit un CSV avec :
- **`prompt_ready`** : le prompt complet à coller dans un chat LLM
- **`llm_answer`** : colonne vide à remplir manuellement avec la réponse du LLM

La colonne `text` brute est exclue pour alléger le fichier.

In [1]:
import sys
import pandas as pd
from pathlib import Path

# Ajouter src/ au path pour importer prompts.py
sys.path.insert(0, str(Path('..').resolve() / 'src'))
from run1_prompts import build_user_prompt, SYSTEM_PROMPT

In [2]:
# Charger les données
df = pd.read_parquet('../data/raw/swissdox_input.parquet')
print(f"Articles chargés : {len(df):,}")
df.head(2)

Articles chargés : 8,787

,article_id,title,lead,text,pubtime,medium_code,medium_name,rubric,regional,doctype,doctype_description,language,char_count,dateline
0,0001de76-bb46-1fd0-ff60-980d765e15a8,Mega-Angriff legt Schweizer Seiten lahm: Hacke...,NoName057(16) bekennt sich zu DDoS-Angriffen a...,NoName057(16) bekennt sich zu DDoS-Angriffen a...,2025-01-21,ZWAO,20 minuten online,,None,WWE,Online medium,de,2666,
1,000658f2-9b7b-c9b4-9592-008f8f4d0b54,Vers la fin des vols en classe affaires pour l...,Privilèges Albert Rösti propose de réviser les...,Privilèges Albert Rösti propose de réviser les...,2025-09-30,HEU,24 heures,Actualités,None,PRD,Regional daily newspaper,fr,1612,

In [3]:
# Construire la colonne prompt_ready (system prompt + user prompt fusionnés)
df['prompt_ready'] = df.apply(
    lambda row: SYSTEM_PROMPT + "\n\n" + build_user_prompt(row, 'text'), axis=1
)

# Ajouter la colonne vide pour les réponses LLM
df['llm_answer'] = ''

print(f"Exemple de prompt_ready pour le premier article :")
print("-" * 60)
print(df['prompt_ready'].iloc[0])

Exemple de prompt_ready pour le premier article :
------------------------------------------------------------
You are a media analysis assistant specialised in Swiss public affairs.
Your task is to screen a newspaper article for two things and, when relevant, produce a concise summary.

--- STEP 1 — SWISS CONTEXT ---
Does the article have any connection to Switzerland?
Count as YES: any reference to a Swiss institution, official, law, city, company, currency, place, or affair — even minor.
Count as NO: zero connection to Switzerland.

--- STEP 2 — CRITICISM ---
(Evaluate only if STEP 1 = YES; otherwise answer NO.)

Is there any sentence or passage in the article where someone expresses a negative judgment about any person, institution, or entity?
A negative judgment = any statement that someone's conduct, decision, proposal, or inaction is wrong, harmful, inadequate, excessive, unjustified, or counterproductive.
A single qualifying sentence anywhere in the article is enough — the criticism does not need to be the main topic.
The source can be anyone: a quoted actor, a paraphrased source, an opinion-piece author, a letter-writer, or the journalist through their own editorial framing.
If the article contains multiple independent sections (e.g. letters to the editor), evaluate each section separately — one qualifying section makes the whole answer YES.

Answer NO only if the entire article is neutral factual reporting with no negative judgment anywhere.

--- STEP 3 — CRITICISM SUMMARY ---
(Produce only if STEP 2 = YES; otherwise answer N/A.)
Write one paragraph summarising the criticism. The paragraph must cover:

  SOURCE — name every actor whose statements, quotes, or paraphrased views make the critical argument, with their title and affiliation as stated in the article. Use "journalist [name if given]" ONLY if no external actor is quoted, named, or paraphrased as making the criticism.

  TARGET — name the entity being criticised as specifically as the article allows (e.g. "the EDA", "the city of Zurich", "the FINMA", "Credit Suisse CEO X"). Never use vague labels like "the authorities" or "the government" when the article names a specific entity.

  SUBSTANCE — the specific conduct, decision, proposal, or inaction being condemned.

Preserve all actor names, roles, and factual details. Do not paraphrase away specifics.

--- OUTPUT FORMAT ---
Respond with EXACTLY these 3 lines and nothing else:

SWISS_CONTEXT: YES or NO
CRITICISM: YES or NO
CRITICISM_SUMMARY: [one paragraph] or N/A

Do not add any explanation, preamble, or extra line.

Analyse the following newspaper article according to the instructions above.

Article:
NoName057(16) bekennt sich zu DDoS-Angriffen auf Schweizer Banken und Gemeinden. Die pro-russische Gruppe testet die Internet-Infrastruktur.

Jonas Bucher

Darum gehts Eine russische Hackergruppe hat erneut Schweizer Websites angegriffen.

Betroffen sind die Zürcher und Waadtländer Kantonalbanken sowie mehrere Gemeinden.

Die Gruppe NoName057(16) bekennt sich zu den DDoS-Angriffen auf der Plattform X.

Die Angriffe sind politisch motiviert und richten sich gegen Länder, die die Ukraine unterstützen.

Seit Monaten werden Websites von Schweizer Banken und Behörden Ziel von sogenannten DDoS-Angriffen . Am Dienstag traf es erneut die Zürcher Kantonalbank, deren Website nicht erreichbar ist. Auch die Waadtländer Kantonalbank ist betroffen.

Auf der Plattform X bekannte sich die pro-russische Hackergruppe NoName057(16) zu den Angriffen. «Wir testen weiterhin die Belastbarkeit der Schweizer Internet-Infrastruktur», schreibt die Gruppe in einem Beitrag, in dem sie auch weitere betroffene Websites aufführt. Zu den Zielen zählten diesmal mehrere Gemeinden, darunter Luzern, Adligenswil, Kriens und Ebikon.

Websites durch massenhafte Anfragen lahmgelegt Eine DDoS-Attacke (Distributed Denial of Service) ist ein gezielter Cyberangriff, bei dem eine Website, ein Server oder ein Netzwerk durch massenhafte Anfragen überlastet wird, sodass reguläre Nutzer keinen Zugriff mehr haben.

Wie besorgt bist du über Cyberangriffe auf Schweizer Websites?

Sehr besorgt, das könnte ernste Folgen haben.

Ein wenig besorgt, aber ich vertraue auf die Sicherheitsmassnahmen.

Nicht besorgt, das betrifft mich nicht direkt.

Ich habe keine Meinung dazu.

Hackergruppe seit 2022 aktiv Die Hackergruppe NoName057(16) tritt seit 2022 mit Cyberangriffen auf europäische Länder und Institutionen in Erscheinung. Sie nutzt vor allem DDoS-Attacken, um Websites von Behörden, Unternehmen und kritischer Infrastruktur lahmzulegen. Die Gruppe rechtfertigt ihre Angriffe oft politisch und gibt an, westliche Länder für ihre Unterstützung der Ukraine im Krieg bestrafen zu wollen. Ihre Aktivitäten und Bekennerschreiben veröffentlicht sie regelmäßig auf Plattformen wie Telegram und X.

NoName057(16) agiert meist in Form eines losen Netzwerks, dessen Mitglieder anonym bleiben. Ihre Angriffe richten sich gezielt gegen Staaten, die sie als «unfreundlich» gegenüber Russland wahrnehmen, darunter die Deutschland, Polen und die baltischen Staaten – und eben auch die Schweiz.

In [4]:
# Supprimer la colonne text brute et exporter
cols_to_keep = [c for c in df.columns if c != 'text']
df_out = df[cols_to_keep]

out_path = Path('../data/raw/swissdox_prompts.csv')
df_out.to_csv(out_path, index=False)

print(f"Fichier exporté : {out_path}")
print(f"Colonnes : {df_out.columns.tolist()}")
print(f"Lignes : {len(df_out):,}")

Fichier exporté : ../data/raw/swissdox_prompts.csv
Colonnes : ['article_id', 'title', 'lead', 'pubtime', 'medium_code', 'medium_name', 'rubric', 'regional', 'doctype', 'doctype_description', 'language', 'char_count', 'dateline', 'prompt_ready', 'llm_answer']
Lignes : 8,787

In [5]:
# Aperçu du résultat final
df_out[['article_id', 'medium_name', 'pubtime', 'prompt_ready', 'llm_answer']].head(3)

,article_id,medium_name,pubtime,prompt_ready,llm_answer
0,0001de76-bb46-1fd0-ff60-980d765e15a8,20 minuten online,2025-01-21,You are a media analysis assistant specialised...,
1,000658f2-9b7b-c9b4-9592-008f8f4d0b54,24 heures,2025-09-30,You are a media analysis assistant specialised...,
2,0009a49c-b08a-7e36-0544-bdbeaec73b95,20 minuten online,2025-09-21,You are a media analysis assistant specialised...,